### ISSUE TITLE
Avoid storing possible choices when adding data.

### ISSUE THREAD

**Issue by frafra** [geopaparazzi/smash#129]
For each point added to the map, Smash stores the whole form, including all the possible values and not just the one being selected. This can lead to an increased resource usage.

**Comment by moovida** [comment]
HI @frafra , I understand you and you are not the first one proposing this.

But the choice has been made because of a reason.

I want the forms to be modifiable also in future. This means also when loading a project from another person without you having that particular form available. The form is taken from inside the db and still presents all options. 

At the time (and still now) we are convinced that this is an important point for data consistency over time. So we decided to "loose" on the side of the storage space cutdown.

**Comment by frafra** [comment]
Thank you for the explanation.

A possible improvement would then be having some kind of compression, to avoid data duplication I guess, but it would require extra logic, like having a table with unique set of forms to refer, or using the zjson on postgres (I am writing this down just for future reference).

**Comment by frafra** [comment]
I think that the logic could be kept as it is, but the form could just be stored in a different place. There could be a list of forms with unique IDs; if a form is not there, it can be added; the notes would refer to a form via ID.

**Comment by moovida** [comment]
This is now supported in dynamic layers. Also, urls are now supported, so that would work also in classic notes
