### ISSUE TITLE
How to do visualization and editing of one type of theming by unique values

### ISSUE THREAD

**Issue by killerm250m** [geopaparazzi/smash#143]
In Smash manual [here](https://www.geopaparazzi.org/smash/index.html#_style_a_geopackage_layer)  
I am using a multi polygon layer but for some unknown reason, There is no option to add rules.

**Comment by moovida** [comment]
Hmmm, that sounds like a bug? SMASH doesn't support editing of "multi" geometries, but should support styling. If you can provide me an example db to reproduce your issue I will look into it.

**Comment by killerm250m** [comment]
Sure
[Here you go](https://drive.google.com/file/d/1p2ZITR7vyZX-sLqcFQTHX6V8OnSWoiN5/view?usp=sharing)

**Comment by killerm250m** [comment]
Hi @moovida  can you give me this layer so I can learn more about it regarding how it parsed from xml

**Comment by killerm250m** [comment]
Hi @moovida can you give me this layer so I can learn more about it regarding how it parsed from XML
![sld_12_theme_map](https://user-images.githubusercontent.com/24648104/133049759-76ea64a2-82fe-4a2a-bae3-cc1c8d150177.jpeg)

**Comment by moovida** [comment]
Hi @killerm250m , sorry for the lag in my responses. I am trying within work stuff. 

The XML is the OGC SLD standard (a sub-piece of it). The parsing and creation of this is done in this library:
https://pub.dev/packages/dart_hydrologis_utils

You do not see the rules, because at the moment there is no rules creator wizard. It only works if the rules already exist. Then they can be modified. 

There are a set of example files here: https://github.com/moovida/dart_hydrologis_utils/tree/master/test/files/sld

And here in the tests you can find how to write new rules in code (for example to create an initial ruleset): https://github.com/moovida/dart_hydrologis_utils/blob/master/test/dart_hydrologis_utils_test.dart#L182

Hope that helps.

**Comment by killerm250m** [comment]
What a generous replay!
Thank you very much .
