### ISSUE TITLE
OpenStreetMap map tiles stopped working at the 50m zoom level.

### ISSUE THREAD

**Issue by altilunium** [geopaparazzi/smash#241]
Still works at 100m, but it suddenly goes blank at 50m.

![image](https://github.com/geopaparazzi/smash/assets/70379302/88425da8-12ab-4993-9c7a-0343e20d7f4f)

SMASH version : 1.7.6

**Comment by RobbieNesmith** [comment]
This seems to be due to a discrepancy between three max zoom values:
1. The max zoom level of the map, unrelated to the tile layer
3. The maxZoom of the tile layer, after which it stops rendering
4. The maxNativeZoom of the tile layer, after which it scales the tiles instead of loading the next higher resolution zoom level

By default, the maxZoom for OpenStreetMap is 16, so if you zoom in to level 17 (50m) you get nothing. maxNativeZoom is set at 19.

A workaround is to edit the tile source to have the max layer set as high as you need, capped by the maxNativeZoom of 19. Then remove the OpenStreetMap layer and re-add it to your project to update the settings.

(Opinion) I would expect the max zoom setting when adding a tile source to represent when it stops fetching tiles from that source, but still renders them scaled. So in my opinion, the tile source max zoom should set the tile layer's maxNativeZoom, and the tile layer's maxZoom should be whatever the map uses for the max zoom level.

**Comment by opk12** [comment]
Hello. I edited the OSM source, the zoom was 19 (default), I deleted 19, rewrote it and saved, but no effect :(

**Comment by moovida** [comment]
This one has been fixed in the code base and will be available in the next version.
