### ISSUE TITLE
Option to not start at boot

### ISSUE THREAD

**Issue by opk12** [geopaparazzi/smash#242]
Hi, thank you for this app. It would be nice to have an option to not auto-start when the phone is booted.

**Comment by moovida** [comment]
Hi @opk12 , to be honest I never noticed that there was an autostart of smash on phone boot. 
I can only assume it is due to the gps library, that together with background logging also allows the app to lurk in the background to be awakened?

Do you have any insight or hint on how to change that(if it is that)?

**Comment by opk12** [comment]
Thank you for looking into this. I am using the F-droid version, if that is relevant.

[Here](https://github.com/geopaparazzi/smash/blob/master/android/app/src/main/AndroidManifest.xml#L52C33-L52C86) the manifest matches the lib's instructions from [here](https://github.com/Yukams/background_locator_fixed/wiki/Restart-service-on-device-reboot). I don't have programming experience on Android, sorry.

**Comment by moovida** [comment]
It seems that your fix is the one. Thanks for this.
