### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [geopaparazzi/smash#251]
[smash.zip](https://github.com/geopaparazzi/smash/files/13627505/smash.zip)

I have no idea why there is such difference. Maybe it's caused by some difference in the build environment. Could you please take a look? Thanks!

**Comment by moovida** [comment]
Hi @linsui , I first forgot to upload the apk to the releases page and when I got addressed to it, I probably had run an update of the libs already due to some small changes in the libs :-( So going back to the tag was of no help.

Is the best way to go here to create a new tag (like upgrade slightly the version)?
Thanks

**Comment by moovida** [comment]
:-) The commit was the same, But the local libs possibly not. I guess that was the issue. Will try to repeat the process ... :-/

**Comment by licaon-kter** [comment]
@moovida did you change the signing key? https://monitor.f-droid.org/builds/log/eu.hydrologis.smash/70#site-footer :(


ref: https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html

**Comment by moovida** [comment]
OMG, I must be the numbest f-droid-try-to-put-the-app ever... :-(
I am checking the signing of the last akp and the keystore used there (and added to the fdroid yaml) must have been some android debug keystore that slipped in in a moment of pure desperation.
So, apart of buring myself in shame, how can I fix this?
The best thing to do for me would be to use my usual signing key: 81c62401816220961839db486631058102e7bd3362d757443ab2477d52781d8a
Can I just create a MR changing that line?

Also, what does this mean:
```
disable: https://github.com/geopaparazzi/smash/issues/251#issuecomment-1854455095
```

That this issue blocks it from being built?

Thanks for the patience.

**Comment by licaon-kter** [comment]
Sign it with the same key you did the previous version. Upload new apk. Yes, disable means disabled... until we confirm it fixed

**Comment by moovida** [comment]
I would if I could. The problem is that the apk was build with android studio at that time. And I suppose it used an automatically generated debug keystore that resides on a pc I do not own anymore (has been reset and changed owner). Also the debug keystore (I only noticed from the previous apk signing check) is not safe, if it really is a debug keystore.

**Comment by licaon-kter** [comment]
:( Done, thanks https://gitlab.com/fdroid/fdroiddata/-/commit/e36eb230fa24412a8920424683361046f09defbc

**Comment by moovida** [comment]
I can't thank you guys enough and apologize for all the mess and extra work I created. 🙏
