### ISSUE TITLE
Exporting gpap file via Horton Machine

### ISSUE THREAD

**Issue by tghoward** [geopaparazzi/smash#273]
I typically export .gpap files using the HortonMachine extensions for GVSig (http://www.hortonmachine.org/hydrologis4gvsig_quickstart/hydrologis4gvsig_quickstart.html#_the_geopaparazzi_plugins). I was expecting this would work fine with Smash gpap files too, but it looks like the two project files I have tested it on don't have metadata tables and throw this error:

Process GvSIGMobileDataStore started at: 2024-06-26 11:09:14
java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: metadata)

I successfully fixed this error by grabbing a metadata table from an older .gpap file and adding to the one I was trying to export. The conversion and export went fine. But this is a hack.

My questions:
- Am I missing a step that triggers SMASH to create a metadata table?
- the GVSig extension is older now, should I assume it is being retired? 
- is there an alternate toolbox or export tool that has the same functionality: creating attributed spatial layers and exporting photos from .gpap files?

(hi moovida!)
Best, 
Tim

**Comment by moovida** [comment]
Hi Tim, so good to hear from you. :-)

1) The Hortonmachine does no longe rlive in the gvSIG project, we retired from it a long time ago. But we are working almost daily on the standalone versione of the HM. It basically is the window you saw in gvSIG, but as own application.
In there the converter is updated.

You can download a compiled release here: https://github.com/TheHortonMachine/hortonmachine/releases/tag/hortonmachine-0.10.7
Even if the build is a bit old, if there are issues, just let me know and I will fix and release quickly. 

2) you can also export a gpap project to geopackage from within smash, but there it depends on how your data is structured and might not be your best bet.

3) the survey server now has a 2-side synch of form based notes. On the postgis side the forms are flattened into regular tables with the form keys as columns. I try to show some of it here: https://www.youtube.com/watch?v=lRXou2QnE3s
But then I kow you need to use geopaparazzi, so that also might not be the right one for you.

Hope that helps.

**Comment by tghoward** [comment]
Perfect, thank you!  I tried out the standalone version and it seems to do the trick! Apologies for not trying that out sooner. 
I appreciate your list of the other options too, they may come in handy. 
Best, Tim
